import os

COOKIES_PY_PATH = "cookies.py"  # Write to current directory

print("🍪 Paste your full cookies string below.")
print("👉 After pasting, press Enter and then Ctrl+Z (on Windows) and Enter again to finish.\n")
print("Cookies:")

import sys
cookie_lines = sys.stdin.read().strip()

if not cookie_lines:
    print("❌ No cookies pasted. Exiting.")
    exit()

# Parse cookie string
cookies = {}
for part in cookie_lines.split(";"):
    if "=" in part:
        name, value = part.strip().split("=", 1)
        cookies[name.strip()] = value.strip()

# Save to cookies.py in current directory
with open(COOKIES_PY_PATH, "w", encoding="utf-8") as f:
    f.write("# Auto-generated by cookie_helper.py\n")
    f.write("cookies = {\n")
    for k, v in cookies.items():
        f.write(f"    {repr(k)}: {repr(v)},\n")
    f.write("}\n")

print(f"\n✅ Cookies saved to: {COOKIES_PY_PATH}")
