import os

COOKIES_PY_PATH = os.path.join("scripts", "cookies.py")

print("🍪 Paste your full cookies string below (the one from browser DevTools).")
print("✅ Press Enter TWICE when you're done.\n")

# Multi-line input until blank line
lines = []
while True:
    line = input()
    if line.strip() == "":
        break
    lines.append(line.strip())

cookie_string = " ".join(lines)

if not cookie_string:
    print("❌ No cookies pasted. Exiting.")
    exit()

# Parse string into dictionary
cookies = {}
for part in cookie_string.split(";"):
    if "=" in part:
        name, value = part.strip().split("=", 1)
        cookies[name.strip()] = value.strip()

# Format and write to cookies.py
with open(COOKIES_PY_PATH, "w", encoding="utf-8") as f:
    f.write("# Auto-generated by cookies_helper.py\n")
    f.write("cookies = {\n")
    for k, v in cookies.items():
        f.write(f"    {repr(k)}: {repr(v)},\n")
    f.write("}\n")

print(f"✅ Cookies saved to: {COOKIES_PY_PATH}")
