import streamlit as st
import pandas as pd
from engine import generate_recommendations
import subprocess
import os

st.set_page_config(page_title="Rocksmith Recommender", layout="wide")
st.title("🎸 Rocksmith CDLC Recommender")
st.markdown("Compare your Spotify + Last.fm listening data with your CDLC library.")
# Paste Cookies section
st.sidebar.subheader("🔑 Paste Cookies")
with st.sidebar.expander("Paste and Save CustomForge Cookies"):
    raw_cookies = st.text_area("Paste your entire cookie string here:", height=150)
    if st.button("💾 Save Cookies"):
        def parse_cookie_string(cookie_string):
            cookie_dict = {}
            for pair in cookie_string.split(";"):
                if "=" in pair:
                    key, value = pair.split("=", 1)
                    cookie_dict[key.strip()] = value.strip()
            return cookie_dict

        def save_cookie_file(cookie_dict):
            try:
                from pathlib import Path
                COOKIES_PATH = Path(__file__).resolve().parent / "cookies.py"
                with open(COOKIES_PATH, "w", encoding="utf-8") as f:
                    f.write("# Auto-generated by cookie_helper.py\n")
                    f.write("cookies = {\n")
                    for k, v in cookie_dict.items():
                        f.write(f"    {repr(k)}: {repr(v)},\n")
                    f.write("}\n")
                return True
            except Exception as e:
                st.error(f"❌ Failed to write cookies.py: {e}")
                return False

        parsed = parse_cookie_string(raw_cookies)
        if not parsed:
            st.warning("⚠️ Cookie string is empty or invalid.")
        else:
            missing_keys = [k for k in ["ignition4_session", "ips4_login_key"] if k not in parsed]
            if missing_keys:
                st.warning(f"⚠️ Missing possibly important keys: {', '.join(missing_keys)}")
            if save_cookie_file(parsed):
                st.success("✅ Cookies saved to scripts/cookies.py")

# Initialize session state
if 'recs' not in st.session_state:
    st.session_state.recs = pd.DataFrame()
if 'offset' not in st.session_state:
    st.session_state.offset = 0
if 'min_scrobbles' not in st.session_state:
    st.session_state.min_scrobbles = 0
if 'max_scrobbles' not in st.session_state:
    st.session_state.max_scrobbles = 500
if 'filter_existing' not in st.session_state:
    st.session_state.filter_existing = False
if 'all_filtered' not in st.session_state:
    st.session_state.all_filtered = pd.DataFrame()


# Fixed scrobble slider cap between 1 and 500
slider_cap = 500

# Sidebar options
with st.sidebar:
    st.header("🔧 Settings")
    min_scrobbles = st.slider("Minimum Scrobbles", 1, slider_cap, st.session_state.min_scrobbles)
    max_scrobbles = st.slider("Maximum Scrobbles", 1, slider_cap, st.session_state.max_scrobbles)
    filter_existing = st.checkbox("✅ Only show songs that exist on CustomsForge", value=st.session_state.filter_existing)

# Progress callback
def streamlit_progress_callback():
    progress_bar = st.progress(0)
    status_text = st.empty()

    def callback(current, total, artist, track):
        pct = current / total
        progress_bar.progress(pct)
        status_text.markdown(f"🔍 Checking `{artist}` — `{track}` ({current}/{total})")

    return callback

# Generate button
if st.button("🎯 Generate Recommendations"):
    with st.spinner("Crunching data..."):
        st.session_state.offset = 0
        st.session_state.min_scrobbles = min_scrobbles
        st.session_state.max_scrobbles = max_scrobbles
        st.session_state.filter_existing = filter_existing

        update_cb = streamlit_progress_callback() if filter_existing else None

        all_recs = generate_recommendations(
            top_n=50,
            save=False,
            min_scrobbles=min_scrobbles,
            max_scrobbles=max_scrobbles,
            filter_existing=filter_existing,
            update_progress=update_cb,
        )

        if all_recs.empty:
            st.session_state.recs = pd.DataFrame(columns=['Artist Name(s)', 'Track Name', 'Scrobbles'])
            st.session_state.all_filtered = pd.DataFrame(columns=['Artist Name(s)', 'Track Name', 'Scrobbles'])
        else:
            filtered = all_recs.reset_index(drop=True)
            st.session_state.recs = filtered.head(50)
            st.session_state.all_filtered = filtered



# Load More button (always visible, handles empty state internally)
# Load More button (always visible, fetches next batch correctly)
if st.button("➕ Load 50 More"):
    with st.spinner("Loading more recommendations..."):
        st.session_state.offset += 50
        update_cb = streamlit_progress_callback() if st.session_state.filter_existing else None

        new_recs = generate_recommendations(
            top_n=50,
            save=False,
            min_scrobbles=st.session_state.min_scrobbles,
            max_scrobbles=st.session_state.max_scrobbles,
            filter_existing=st.session_state.filter_existing,
            update_progress=update_cb,
            offset=st.session_state.offset,  # 👈 key to fetching the correct slice
        )

        if not new_recs.empty:
            st.session_state.recs = pd.concat([st.session_state.recs, new_recs], ignore_index=True)
        else:
            st.info("🚫 No more recommendations to load.")


# Display recommendations
if not st.session_state.recs.empty:
    st.success(f"Showing {len(st.session_state.recs)} recommendations")

    display_cols = ['Artist Name(s)', 'Track Name', 'Scrobbles']
    if 'CustomsForge Link' in st.session_state.recs.columns:
        display_cols.append('CustomsForge Link')

    st.markdown("### 📋 Recommendations")
    st.write(
        st.session_state.recs[display_cols].to_html(escape=False, index=False),
        unsafe_allow_html=True,
    )

    csv = st.session_state.recs[display_cols].to_csv(index=False).encode('utf-8')
    st.download_button("⬇️ Download CSV", csv, "recommendations.csv", "text/csv")


# Update CDLC Library button
if st.button("🔁 Update CDLC Library"):
    try:
        script_path = os.path.join(os.path.dirname(__file__), "update_cdlc_library.py")
        result = subprocess.run(["python", script_path], check=True, capture_output=True, text=True)
        st.success("✅ CDLC library updated successfully.")
        st.text(result.stdout)
    except subprocess.CalledProcessError as e:
        st.error("❌ Failed to update CDLC library.")
        st.text(e.stderr)
