import streamlit as st
import pandas as pd
from engine import generate_recommendations
import subprocess
import os
from pathlib import Path

def refresh_lastfm_data():
    try:
        current_dir = Path(__file__).resolve().parent
        fetch_script = current_dir.parent / "scripts" / "fetch_lastfm_artists.py"

        result = subprocess.run(
            ["python", str(fetch_script)],
            capture_output=True,
            text=True,
            check=True
        )
        st.success("✅ Last.fm artist data refreshed successfully!")
        st.text(result.stdout)
    except subprocess.CalledProcessError as e:
        st.error("❌ Failed to refresh Last.fm data.")
        st.text(e.stderr)
    except Exception as e:
        st.error(f"❌ Unexpected error: {e}")

st.set_page_config(page_title="Rocksmith Recommender", layout="wide")
st.title("🎸 Rocksmith CDLC Recommender")
st.markdown("Compare your Spotify + Last.fm listening data with your CDLC library.")

# Refresh Last.fm artist data
st.sidebar.subheader("🎵 Last.fm Sync")
if st.sidebar.button("🔄 Refresh Last.fm Data"):
    refresh_lastfm_data()

# Refresh Spotify Liked
from pathlib import Path

spotify_script_path = Path(__file__).parent / "fetch_spotify_liked.py"

if st.sidebar.button("🔄 Refresh Spotify Liked Songs"):
    with st.spinner("Fetching your liked Spotify tracks..."):
        try:
            result = subprocess.run(
                ["python", str(spotify_script_path)],
                capture_output=True,
                text=True,
                check=True,
            )
            st.success("✅ Spotify liked songs updated successfully!")
            st.text(result.stdout)
        except subprocess.CalledProcessError as e:
            st.error("❌ Failed to refresh Spotify liked songs.")
            st.text(e.stderr)

# Paste Cookies section
st.sidebar.subheader("🔑 Paste Cookies")
with st.sidebar.expander("Paste and Save CustomForge Cookies"):
    raw_cookies = st.text_area("Paste your entire cookie string here:", height=150)
    if st.button("💾 Save Cookies"):
        def parse_cookie_string(cookie_string):
            cookie_dict = {}
            for pair in cookie_string.split(";"):
                if "=" in pair:
                    key, value = pair.split("=", 1)
                    cookie_dict[key.strip()] = value.strip()
            return cookie_dict

        def save_cookie_file(cookie_dict):
            try:
                from pathlib import Path
                COOKIES_PATH = Path(__file__).resolve().parent / "cookies.py"
                with open(COOKIES_PATH, "w", encoding="utf-8") as f:
                    f.write("# Auto-generated by cookie_helper.py\n")
                    f.write("cookies = {\n")
                    for k, v in cookie_dict.items():
                        f.write(f"    {repr(k)}: {repr(v)},\n")
                    f.write("}\n")
                return True
            except Exception as e:
                st.error(f"❌ Failed to write cookies.py: {e}")
                return False

        parsed = parse_cookie_string(raw_cookies)
        if not parsed:
            st.warning("⚠️ Cookie string is empty or invalid.")
        else:
            missing_keys = [k for k in ["ignition4_session", "ips4_login_key"] if k not in parsed]
            if missing_keys:
                st.warning(f"⚠️ Missing possibly important keys: {', '.join(missing_keys)}")
            if save_cookie_file(parsed):
                st.success("✅ Cookies saved to scripts/cookies.py")

# Initialize session state
if 'recs' not in st.session_state:
    st.session_state.recs = pd.DataFrame()
if 'offset' not in st.session_state:
    st.session_state.offset = 0
if 'min_scrobbles' not in st.session_state:
    st.session_state.min_scrobbles = 0
if 'max_scrobbles' not in st.session_state:
    st.session_state.max_scrobbles = 500
if 'filter_existing' not in st.session_state:
    st.session_state.filter_existing = False
if 'all_filtered' not in st.session_state:
    st.session_state.all_filtered = pd.DataFrame()


# Fixed scrobble slider cap between 1 and 500
slider_cap = 500

# Sidebar options
with st.sidebar:
    st.header("🔧 Settings")
    
    # Sliders
    min_slider = st.slider("Minimum Scrobbles", 0, slider_cap, st.session_state.min_scrobbles)
    max_slider = st.slider("Maximum Scrobbles", 0, slider_cap, st.session_state.max_scrobbles)
    
    # Optional overrides
    st.markdown("#### 🎯 Manual Override (optional)")
    manual_min = st.number_input("Set Min Scrobbles", min_value=0, max_value=slider_cap, value=0, step=1)
    manual_max = st.number_input("Set Max Scrobbles", min_value=0, max_value=slider_cap, value=0, step=1)

    filter_existing = st.checkbox("✅ Only show songs that exist on CustomsForge", value=st.session_state.filter_existing)

# Progress callback
def streamlit_progress_callback():
    progress_bar = st.progress(0)
    status_text = st.empty()

    def callback(current, total, artist, track):
        pct = current / total
        progress_bar.progress(pct)
        status_text.markdown(f"🔍 Checking `{artist}` — `{track}` ({current}/{total})")

    return callback

# Custom input for number of recommendations
custom_rec_count = st.number_input(
    "Number of recommendations to generate", 
    min_value=1, 
    max_value=1000, 
    value=50, 
    step=10
)

# Generate button
if st.button("🎯 Generate Recommendations"):
    with st.spinner("Crunching data..."):
        st.session_state.offset = custom_rec_count  # 👈 Set offset to match initial display count
        # Apply override only if values are non-zero
        effective_min = manual_min if manual_min > 0 else min_slider
        effective_max = manual_max if manual_max > 0 else max_slider
        
        # Save to session state
        st.session_state.min_scrobbles = effective_min
        st.session_state.max_scrobbles = effective_max
        st.session_state.filter_existing = filter_existing

        update_cb = streamlit_progress_callback() if filter_existing else None

        all_recs = generate_recommendations(
            top_n=custom_rec_count,
            save=False,
            min_scrobbles=effective_min,
            max_scrobbles=effective_max,
            filter_existing=filter_existing,
            update_progress=update_cb,
        )

        if all_recs.empty:
            st.session_state.recs = pd.DataFrame(columns=['Artist Name(s)', 'Track Name', 'Scrobbles'])
            st.session_state.all_filtered = pd.DataFrame(columns=['Artist Name(s)', 'Track Name', 'Scrobbles'])
        else:
            filtered = all_recs.reset_index(drop=True)
            st.session_state.recs = filtered.head(custom_rec_count)  # 👈 Display as many as requested
            st.session_state.all_filtered = filtered

# Load More button (always visible, fetches next batch correctly)
if st.button("➕ Load 50 More"):
    with st.spinner("Loading more recommendations..."):
        st.session_state.offset += 50
        update_cb = streamlit_progress_callback() if st.session_state.filter_existing else None

        new_recs = generate_recommendations(
            top_n=50,
            save=False,
            min_scrobbles=st.session_state.min_scrobbles,
            max_scrobbles=st.session_state.max_scrobbles,
            filter_existing=st.session_state.filter_existing,
            update_progress=update_cb,
            offset=st.session_state.offset,
        )

        if not new_recs.empty:
            st.session_state.recs = pd.concat([st.session_state.recs, new_recs], ignore_index=True)
        else:
            st.info("🚫 No more recommendations to load.")

# Display recommendations
if not st.session_state.recs.empty:
    st.success(f"Showing {len(st.session_state.recs)} recommendations")

    display_cols = ['Artist Name(s)', 'Track Name', 'Scrobbles']
    display_df = st.session_state.recs.copy()

    # ✅ Format only for rendering (not modifying the session data)
    if 'CustomsForge Link' in display_df.columns:
        display_df['CustomsForge Link'] = display_df['CustomsForge Link'].apply(
            lambda url: f'<a href="{url}" target="_blank">🔗 View CDLC</a>'
            if pd.notna(url) and str(url).startswith("http") else ''
        )
        display_cols.append('CustomsForge Link')

    st.markdown("### 📋 Recommendations")
    st.write(display_df[display_cols].to_html(escape=False, index=False), unsafe_allow_html=True)

    csv = st.session_state.recs[display_cols].to_csv(index=False).encode('utf-8')
    st.download_button("⬇️ Download CSV", csv, "recommendations.csv", "text/csv")


# Update CDLC Library button
if st.button("🔁 Update CDLC Library"):
    try:
        script_path = os.path.join(os.path.dirname(__file__), "update_cdlc_library.py")
        result = subprocess.run(["python", script_path], check=True, capture_output=True, text=True)
        st.success("✅ CDLC library updated successfully.")
        st.text(result.stdout)
    except subprocess.CalledProcessError as e:
        st.error("❌ Failed to update CDLC library.")
        st.text(e.stderr)
